<?xml version="1.0"?>
<package format="3">
  <name>amr_learning</name><version>0.1.0</version>
  <description>Educational ROS 2 communication examples.</description>
  <maintainer email="maintainer@example.com">AMR Robotics Lab</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend><depend>rclpy</depend><depend>std_msgs</depend>
  <depend>std_srvs</depend><depend>action_tutorials_interfaces</depend>
  <exec_depend>launch</exec_depend><exec_depend>launch_ros</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
